
import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import FooterSection from "@/components/fotter";
import TopNavbar from "@/components/TopNavbar";
import MainNav from "@/components/MainNavbar";

export const metadata: Metadata = {
  title: "Taskco Tech",
  description: "Generated by create SRA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <CartProvider>
        <TopNavbar></TopNavbar>
        <MainNav></MainNav>

        {children}
       <FooterSection></FooterSection>
        
        </CartProvider>
        </body>
    </html>
  );
}