import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Taskco Tech",
  description: "Generated by create SRA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col antialiased">
        {children}
      </body>
    </html>
  );
}